# -*- coding: utf-8 -*-

ResourceType = {
    'abstract':[u'abstract'],
    'sommaire':[u'abstract'],
    'agreement':[u'agreement'],
    'entente':[u'agreement'],
    'agreement - contractual material':[u'contractual_material'],
    'entente - contenu contractuel':[u'contractual_material'],
    'agreement - intergovernmental agreement':[u'intergovernmental_agreement'],
    'entente - entente intergouvernementale':[u'intergovernmental_agreement'],
    'agreement - lease':[u'lease'],
    'entente - bail':[u'lease'],
    'agreement - memorandum of understanding':[u'memorandum_of_understanding'],
    'entente - protocole d’entente':[u'memorandum_of_understanding'],
    'agreement - nondisclosure agreement':[u'nondisclosure_agreement'],
    'entente - accord de non divulgation':[u'nondisclosure_agreement'],
    'agreement - service-level agreement':[u'servicelevel_agreement'],
    'entente - entente de niveau de service':[u'servicelevel_agreement'],
    'affidavit':[u'affidavit'],
    'affidavit':[u'affidavit'],
    'application':[u'application'],
    'application':[u'application'],
    'api':[u'api'],
    'api':[u'api'],
    'architectural or technical design':[u'architectural_or_technical_design'],
    'conception architecturale ou technique':[u'architectural_or_technical_design'],
    'article':[u'article'],
    'article':[u'article'],
    'assessment':[u'assessment'],
    'évaluation':[u'assessment'],
    'assessment - audit':[u'audit'],
    'évaluation - audit':[u'audit'],
    'assessment - environmental assessment':[u'environmental_assessment'],
    'évaluation - évaluation environnementale':[u'environmental_assessment'],
    'assessment - examination':[u'examination'],
    'évaluation - examen':[u'examination'],
    'assessment - gap assessment':[u'gap_assessment'],
    'évaluation - évaluation des écarts':[u'gap_assessment'],
    'assessment - lessons learned':[u'lessons_learned'],
    'évaluation - leçons apprises':[u'lessons_learned'],
    'assessment - performance indicator':[u'performance_indicator'],
    'évaluation - indicateur de rendement':[u'performance_indicator'],
    'assessment - risk assessment':[u'risk_assessment'],
    'évaluation - évaluation des risques':[u'risk_assessment'],
    'biography':[u'biography'],
    'biographie':[u'biography'],
    'briefing material':[u'briefing_material'],
    'matériel de breffage':[u'briefing_material'],
    'briefing material - backgrounder':[u'backgrounder'],
    'matériel de breffage - précis d’information':[u'backgrounder'],
    'business case':[u'business_case'],
    'analyse de rentabilisation':[u'business_case'],
    'claim':[u'claim'],
    'réclamation':[u'claim'],
    'comments':[u'comments'],
    'commentaires':[u'comments'],
    'conference proceedings':[u'conference_proceedings'],
    'actes de la conférence':[u'conference_proceedings'],
    'consultation':[u'consultation'],
    'consultation':[u'consultation'],
    'contact information':[u'contact_information'],
    'coordonnées':[u'contact_information'],
    'correspondence':[u'correspondence'],
    'correspondance':[u'correspondence'],
    'correspondence - ministerial correspondence':[u'ministerial_correspondence'],
    'correspondance - correspondance ministérielle':[u'ministerial_correspondence'],
    'correspondence - memorandum':[u'memorandum'],
    'correspondance - note de service':[u'memorandum'],
    'dataset':[u'dataset'],
    'jeu de données':[u'dataset'],
    'delegation of authority':[u'delegation_of_authority'],
    'délégation des pouvoirs':[u'delegation_of_authority'],
    'educational material':[u'educational_material'],
    'matériel pédagogique':[u'educational_material'],
    'employment opportunity':[u'employment_opportunity'],
    'possibilité d’emploi':[u'employment_opportunity'],
    'event':[u'event'],
    'événement':[u'event'],
    'fact sheet':[u'fact_sheet'],
    'feuille de renseignements':[u'fact_sheet'],
    'financial material':[u'financial_material'],
    'document financier':[u'financial_material'],
    'financial material - budget':[u'budget'],
    'document financier - budget':[u'budget'],
    'financial material - funding proposal':[u'funding_proposal'],
    'document financier - proposition de financement':[u'funding_proposal'],
    'financial material - invoice':[u'invoice'],
    'document financier - facture':[u'invoice'],
    'financial material - financial statement':[u'financial_statement'],
    'document financier - états financiers':[u'financial_statement'],
    'form':[u'form'],
    'formulaire':[u'form'],
    'framework':[u'framework'],
    'cadre':[u'framework'],
    'geospatial material':[u'geospatial_material'],
    'matériel géospatial':[u'geospatial_material'],
    'guide':[u'guide'],
    'guide':[u'guide'],
    'guide - best practices':[u'best_practices'],
    'guide - pratiques exemplaires':[u'best_practices'],
    'intellectual property statement':[u'intellectual_property_statement'],
    'énoncé sur la propriété intellectuelle':[u'intellectual_property_statement'],
    'legal complaint':[u'legal_complaint'],
    'plainte légale':[u'legal_complaint'],
    'legal opinion':[u'legal_opinion'],
    'avis juridique':[u'legal_opinion'],
    'legislation and regulations':[u'legislation_and_regulations'],
    'lois et règlements':[u'legislation_and_regulations'],
    'licenses and permits':[u'licenses_and_permits'],
    'licences et permis':[u'licenses_and_permits'],
    'literary material':[u'literary_material'],
    'ouvrages littéraires':[u'literary_material'],
    'media release - statement':[u'statement'],
    'communiqué de presse - énoncé':[u'statement'],
    'media release':[u'media_release'],
    'communiqué de presse':[u'media_release'],
    'meeting material':[u'meeting_material'],
    'documentation de la réunion':[u'meeting_material'],
    'meeting material - agenda':[u'agenda'],
    'documentation de la réunion - programme':[u'agenda'],
    'meeting material - minutes':[u'minutes'],
    'documentation de la réunion - procès-verbaux':[u'minutes'],
    'memorandum to cabinet':[u'memorandum_to_cabinet'],
    'mémoire au cabinet':[u'memorandum_to_cabinet'],
    'multimedia resource':[u'multimedia_resource'],
    'ressource multimédia':[u'multimedia_resource'],
    'notice':[u'notice'],
    'avis':[u'notice'],
    'organizational description':[u'organizational_description'],
    'description organisationnelle':[u'organizational_description'],
    'plan':[u'plan'],
    'plan':[u'plan'],
    'plan - business plan':[u'business_plan'],
    'plan - plan d’activités':[u'business_plan'],
    'plan - strategic plan':[u'strategic_plan'],
    'plan - plan stratégique':[u'strategic_plan'],
    'policy':[u'policy'],
    'politique':[u'policy'],
    'policy - white paper':[u'white_paper'],
    'politique - livre blanc':[u'white_paper'],
    'presentation':[u'presentation'],
    'présentation':[u'presentation'],
    'procedure':[u'procedure'],
    'procédure':[u'procedure'],
    'profile':[u'profile'],
    'profil':[u'profile'],
    'project material':[u'project_material'],
    'documents du projet':[u'project_material'],
    'project material - project charter':[u'project_charter'],
    'documents du projet - charte de projet':[u'project_charter'],
    'project material - project plan':[u'project_plan'],
    'documents du projet - plan du projet':[u'project_plan'],
    'project material - project proposal':[u'project_proposal'],
    'documents du projet - proposition de projet':[u'project_proposal'],
    'promotional material':[u'promotional_material'],
    'documents promotionnels':[u'promotional_material'],
    'publication':[u'publication'],
    'publication':[u'publication'],
    'q & a - faq':[u'faq'],
    'q et r - foire aux questions':[u'faq'],
    'record of decision':[u'record_of_decision'],
    'compte rendu des décisions':[u'record_of_decision'],
    'report':[u'report'],
    'rapport':[u'report'],
    'report - annual report':[u'annual_report'],
    'rapport - rapport annuel':[u'annual_report'],
    'report - interim report':[u'interim_report'],
    'rapport - rapport d’étape':[u'interim_report'],
    'research proposal':[u'research_proposal'],
    'projet de recherche':[u'research_proposal'],
    'resource list':[u'resource_list'],
    'liste de référence':[u'resource_list'],
    'routing slip':[u'routing_slip'],
    'bordereau d’acheminement':[u'routing_slip'],
    'social media resource - blog entry':[u'blog_entry'],
    'ressources des médias sociaux - entrée de blogue':[u'blog_entry'],
    'sound recording':[u'sound_recording'],
    'enregistrement sonore':[u'sound_recording'],
    'specification':[u'specification'],
    'spécification':[u'specification'],
    'statistics':[u'statistics'],
    'statistiques':[u'statistics'],
    'still image':[u'still_image'],
    'image fixe':[u'still_image'],
    'submission':[u'submission'],
    'présentation':[u'submission'],
    'survey':[u'survey'],
    'sondage':[u'survey'],
    'terminology':[u'terminology'],
    'terminologie':[u'terminology'],
    'terms of reference':[u'terms_of_reference'],
    'mandat':[u'terms_of_reference'],
    'tool':[u'tool'],
    'outil':[u'tool'],
    'training material':[u'training_material'],
    'matériel didactique':[u'training_material'],
    'transcript':[u'transcript'],
    'transcription':[u'transcript'],
    'website':[u'website'],
    'site web':[u'website'],
    'web service':[u'web_service'],
    'service web':[u'web_service'],
    'workflow':[u'workflow'],
    'flux des travaux':[u'workflow']
}